spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:chat-server
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
